/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AESGCMJNI */

#ifndef _Included_AESGCMJNI
#define _Included_AESGCMJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AESGCMJNI
 * Method:    callDecrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_AESGCMJNI_callDecrypt
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
